/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.10 */
package ex2;

public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMUL = 4;
  public int JJTDIV = 5;
  public int JJTTERM = 6;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=88c1bfb528f511a998991c02717a26a1 (do not edit this line) */
